name: Build Project

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GodotDesktop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux, mac]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: GGJO21
          preset: ${{ matrix.platform }}
          debugMode: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }} 

  GodotWeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: GGJO21
          preset: html5
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - html5
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }} 
